### ISSUE TITLE
fMRIPrep: EuskalIBUR

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/open-multi-echo-data#18]
## Location

https://openneuro.org/datasets/ds003192

## Basic info

- 7 participants
- 10 sessions
- BOLD data
    - 5 echoes
    - TR = 1.5
    - Tasks: breath-hold, resting-state (not uploaded), motor (not uploaded), localizer (not uploaded)
    - Physio data: cardiac, respiration, respiratory CO2, respiratory O2
- T1w (MP2RAGE I think)
- T2w

**Comment by tsalo** [comment]
@smoia @eurunuela I just wanted to follow up from https://github.com/ME-ICA/tedana/issues/778. Do you know if the other Euskalibur data (e.g., resting-state, motor task, localizer task) will be uploaded to OpenNeuro at some point?

**Comment by smoia** [comment]
Hey there!
They will, we're just very slow in processing them and publishing something about the dataset (mainly my fault). Just keep faith in the process :rofl: .

We did not saved the K-space, nor the phase component, unfortunately.

**Comment by tsalo** [comment]
Is there a timeline for any of the other tasks? If you don't expect to upload anything in the next couple of months, I might process the breath-hold data for this project and add in the other tasks as they get added to OpenNeuro. It could actually be a good chance to improve my datalad skills.

I figured the k-space data would be a long shot. The only groups that seem to keep their k-space data are the massive consortia, like HBCD.

**Comment by eurunuela** [comment]
> Is there a timeline for any of the other tasks? If you don't expect to upload anything in the next couple of months, I might process the breath-hold data for this project and add in the other tasks as they get added to OpenNeuro. It could actually be a good chance to improve my datalad skills.

If I were you I would start with the breath-hold data for now.
